### ISSUE TITLE
Text list - extra space for second level 

### ISSUE THREAD

**Issue by dashaversha** [maxi-blocks/maxi-blocks#4270]
### Description

Extra space is appearing while add second level in text list.

### Step-by-step reproduction instructions

1. Add text (2 line is enough)
2. Use Text list instrument,use no order one 
3. Add 2 level
4. Change no order for order one

### Screenshots, screen recording, code snippet

https://jam.dev/c/a7aec1d4-7c24-44de-a923-82db8cdbf320
![image](https://user-images.githubusercontent.com/116658168/214600247-8f9f6010-a8ab-4017-b6bf-7bc0b1fa9672.png)

**Comment by Olekrut** [comment]
@elzadj After WP 6.4 we can't have second list level anymore.
so you can close it if correct
