### ISSUE TITLE
Image`s caption bug

### ISSUE THREAD

**Issue by dashaversha** [maxi-blocks/maxi-blocks#4629]
### Description

Image`s caption bug

### Step-by-step reproduction instructions

1. Add image
2. Add caption
3. Change colour 
4. Change caption 
5. Change color again 

### Screenshots, screen recording, code snippet

https://jam.dev/c/fd936f08-4404-437b-a1c8-25a55da15ddf

**Comment by kyrapieterse** [comment]
https://jam.dev/c/5c9f93f8-fb32-4409-838f-efff579d5f7f

**Comment by Fybex** [comment]
able to reproduce

**Comment by Fybex** [comment]
it's possible to reproduce if to change colour very fast after changing caption content

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/c2eb0053-ca3f-45f1-850b-f873203a6c03
