### ISSUE TITLE
Accessibility 

### ISSUE THREAD

**Issue by kyrapieterse** [maxi-blocks/maxi-blocks#4858]
### Description

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by myroslavve** [comment]
Split this up into smaller issues: 
https://github.com/maxi-blocks/maxi-blocks/issues/5511
https://github.com/maxi-blocks/maxi-blocks/issues/5512
For focus indicators, reopened https://github.com/maxi-blocks/maxi-blocks/issues/2726
and for aria-label, https://github.com/maxi-blocks/maxi-blocks/issues/5112 was already there.
