### ISSUE TITLE
Weird hover for text on backend

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#4876]
### Step-by-step reproduction instructions

1) paste code
2) check hover for text on backend

### Screenshots, screen recording, code snippet

 https://jam.dev/c/d5038368-a3a1-4342-80a8-bf5e255c9812

### URL and/or Code editor

[weird hover.txt](https://github.com/maxi-blocks/maxi-blocks/files/11497818/weird.hover.txt)

**Comment by kyrapieterse** [comment]
![image](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/3ce2784e-ebdc-4e3a-84c8-156f4f32c05a)
