### ISSUE TITLE
Background opacity bug

### ISSUE THREAD

**Issue by elzadj** [maxi-blocks/maxi-blocks#5010]
### Description

Sometimes the background (usually on hover) is generated with an opacity error like this:

```rgba(var(--maxi-light-color-4,255,74,23),1)),0.9)```

### Step-by-step reproduction instructions

Hard to reproduce, try on https://staging.devdemo.maxiblocks.com
It comes and goes, I couldn't re-create on my local.

Try PTML-PRO-114 and ptml-pro-77

### Screenshots, screen recording, code snippet

![screenshot-staging devdemo maxiblocks com-2023 08 07-16_42_23](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/2dc66982-e902-4288-ac5b-6f628abd7f16)

### URL and/or Code editor

https://staging.devdemo.maxiblocks.com/62503-2/

### How to fix it

Resetting the SCs fixes it. So maybe something goes wrong when we copy an SC to customise it?

**Comment by Fybex** [comment]
Can't reproduce. Closing until it will happen again
