### ISSUE TITLE
Search block reveal - left position

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5023]
### Description

it was fixed by Marko, but i guess, it was again broken by WP 6.3

### Step-by-step reproduction instructions

1) create search block
2) set reveal search - position left
3) check placeholder

### Screenshots, screen recording, code snippet

![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/a12106bb-55ba-40ce-8871-fb55652995a2)

**Comment by Marko64** [comment]
Unable to re-create this now. Maybe it was fixed by WP 6.4 lol. @Olekrut Can you check?

**Comment by Olekrut** [comment]
Probably, yes, fixed by WP 6.4, lol
