### ISSUE TITLE
Maxi block inserter is partially hidden

### ISSUE THREAD

**Issue by elzadj** [maxi-blocks/maxi-blocks#5061]
### Description

Check the screernshot.

### Screenshots, screen recording, code snippet

![screenshot-wordpress local-2023 08 25-15_07_20](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/322295ea-d7cf-4048-bdf6-4e25ccf46e89)

### How to fix it

https://github.com/maxi-blocks/maxi-blocks/blame/996a928c8f7dae9ed43f9376cb3dafe1ea150ae8/src/components/popover/editor.scss#L12C2-L12C2
Weird and not working z-index.

**Comment by Olekrut** [comment]
It was for old theme, i ve tested even 2010theme, but don't see it, so reopen if somebody will notice it again
