### ISSUE TITLE
Repeater warning

### ISSUE THREAD

**Issue by Fybex** [maxi-blocks/maxi-blocks#5093]
### Step-by-step reproduction instructions

1. Activate repeater
2. Add some blocks
3. Reload
4. It will appear in console after reload

### Screenshots, screen recording, code snippet

![image](https://github.com/maxi-blocks/maxi-blocks/assets/46112160/df710596-ece7-483d-adef-9cdb662b738a)

### How to fix it

check `row-maxi/edit.js`, `getInnerBlocksPositions` and `updateInnerBlocksPositions` logic

**Comment by Olekrut** [comment]
cant re-produce it anymore
