### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by kyrapieterse** [maxi-blocks/maxi-blocks#5120]
### Discussed in https://github.com/maxi-blocks/maxi-blocks/discussions/4543

<div type='discussions-op-text'>

<sup>Originally posted by **Marko64** March 14, 2023</sup>
Blocks rendering based on conditions. Example: https://academy.bricksbuilder.io/article/element-conditions/</div>

**Comment by Marko64** [comment]
Duplicate of https://github.com/maxi-blocks/maxi-blocks/issues/4525
