### ISSUE TITLE
Divider height on backend

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5156]
### Description

Divider height difference between VV and VE

### Step-by-step reproduction instructions

1) create row with static height ( 300px for example )
2) create divider 
3) set height 100%
4) compare VV and VE

### Screenshots, screen recording, code snippet

https://jam.dev/c/2be7e4c7-3fc9-43f8-9650-6602cdb2ed14

**Comment by Fybex** [comment]
> I think this is the same issue as: #4103

Unfortunately, no @Marko64, it's different issues 😢
