### ISSUE TITLE
Context loop. Toolbar icon. Accordion

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5159]
### Description

Context Loop in toolbar is active, even if it is disabled. For accordion and pane

### Step-by-step reproduction instructions

1) Create accordion
2) check CL icon in toolbar

### Screenshots, screen recording, code snippet

![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/7fe8f4a3-4ac2-4cd7-acee-7ca01593bb4a)

**Comment by Marko64** [comment]
I'm unable to replicate. Can you share the code please?

**Comment by Olekrut** [comment]
Hmm, Can't re-produce it on master anymore. Only here https://devdemo.maxiblocks.com/accordion-light-pro/
