### ISSUE TITLE
Transform bug on responsive. Interaction builders.

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5161]
### Description

IB for transform is not working correct on responsive

Master

### Step-by-step reproduction instructions

https://scribehow.com/shared/How_to_Edit_and_Transform_a_Post_in_WordPress__myuEOVQTQCyV1bmX6jo5GQ

### Screenshots, screen recording, code snippet

https://jam.dev/c/5af2756a-2517-4286-9932-9fa606d892ba

### URL and/or Code editor

[transform bug. IB.txt](https://github.com/maxi-blocks/maxi-blocks/files/12675921/transform.bug.IB.txt)

**Comment by Fybex** [comment]
It was fixed in #5175 🎉
