### ISSUE TITLE
Moving style card (SC) migrator from dom.js

### ISSUE THREAD

**Issue by elzadj** [maxi-blocks/maxi-blocks#5184]
### Description

We need to move this SC migrator somewhere, or find another solution.
https://github.com/maxi-blocks/maxi-blocks/blob/7842fc2b90daeb5b3f872309e33c7cd66a2e0d3a/src/extensions/dom/dom.js#L280-L348

It runs all the time, that's not good for the general speed.

@Fybex @TeksPeks any ideas?

### Step-by-step reproduction instructions

-

**Comment by elzadj** [comment]
@Fybex could you remind me why we added that migrator in the first place, please?

**Comment by Fybex** [comment]
> @Fybex could you remind me why we added that migrator in the first place, please?

I was added to migrate old SC(before #4780). Also, it automatically updates SC styles to the fixed version after  change in #5018
