### ISSUE TITLE
Need to hide native Gutenberg's toolbar

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5203]
### Description

Appearing native Gutenberg's toolbar due typing in text block

### Step-by-step reproduction instructions

1) create text-block ( the same with button, and i guess, with all blocks, where we can type )
2) type few signs and wait a bit ( don't click anything )

### Screenshots, screen recording, code snippet

https://jam.dev/c/8b03a49e-103a-4257-bf6c-b6eaeed13f85

**Comment by kyrapieterse** [comment]
https://jam.dev/c/651227c9-aa8a-4d52-a63f-cee42d780112
