### ISSUE TITLE
Some of maxi-blocks are not rendering by first time

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5205]
https://jam.dev/c/6658b18f-29a0-4aff-9877-d092312899dd
but have noticed that NC and search block are not rendering by first loading

_Originally posted by @Olekrut in https://github.com/maxi-blocks/maxi-blocks/pull/5204#pullrequestreview-1682686022_

**Comment by elzadj** [comment]
@Olekrut is it for backend and FSE only?

**Comment by Olekrut** [comment]
> @Olekrut is it for backend and FSE only?

yes

**Comment by kyrapieterse** [comment]
We are going to need a deep look into FSE
