### ISSUE TITLE
Scroll is stealing width on M and S preview 

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5214]
### Description

Scroll is stealing width on M and S preview 

### Step-by-step reproduction instructions

1) open template library
2) check width when scroll is visible, on M and S

### Screenshots, screen recording, code snippet

![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/2734417e-c50f-4c22-8e8a-9bc5f90b932f)

**Comment by elzadj** [comment]
@Olekrut Fixed, you probably need to go to https://maxiblocks.com/demo/ and hit CTRL+F5, and then reload the Editor too, to see it.

![Screenshot from 2023-10-26 12-48-23](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/eeb65875-14a1-450c-8c07-b7c5b8e5578b)
