### ISSUE TITLE
WP 6.4-RC2 bugs

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5225]
### Description

1) UI for SC window ( fixed )
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/7784c639-4a15-4059-b8ba-84a43816721c)
2) List has weird padding on backend
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/1a2bcdf9-466b-49c6-83fa-8ef9cd343f2b)
3) colour under pallet does not change
https://jam.dev/c/bf0f0e7f-7989-40d9-ac2c-b5f1e76c9d02
4)  wrong colour pallet in SC
https://jam.dev/c/d6026b31-33f6-4a06-928e-be6646e43b30
5) random horizontal scroll
https://jam.dev/c/b6e4b052-645b-4aa1-b68b-f10f4716dc17

### Step-by-step reproduction instructions

.

**Comment by elzadj** [comment]
Note: text format is broken, so lists don't work

**Comment by elzadj** [comment]
3. colour under pallet does not change
https://jam.dev/c/bf0f0e7f-7989-40d9-ac2c-b5f1e76c9d02

That's the reset colour's preview :D
Maybe we need to group it with the reset button to make it clear.

![screenshot-stagingdemo maxiblocks com-2023 10 31-17_21_24](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/d3d237e9-5c56-4bd8-bb3f-82b4387551a8)

**Comment by elzadj** [comment]
@Olekrut colur for divider works for me. Please esport your current SC to a file, then reset SCs with 

```
wp.data.dispatch('maxiBlocks/style-cards').resetSC()
```

and try again. Add the exported SC file here. Thanks!

**Comment by Olekrut** [comment]
> @Olekrut colur for divider works for me. Please esport your current SC to a file, then reset SCs with

I cant re-produce it as well anymore, this point has been removed
