### ISSUE TITLE
UI bug - cross is cut off

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5226]
### Description

Check cancel cross for image's shape mask

### Step-by-step reproduction instructions

1) create image 
2) enable shape mask
3) check cancel cross

### Screenshots, screen recording, code snippet

![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/49311dc6-2a84-4ef4-bea2-ece961244670)

**Comment by kyrapieterse** [comment]
@dosu-bot suggest a code fix
