### ISSUE TITLE
Sweep: Two reset button in baby toolbar

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5231]
### Description

Need to remove one of reset button in button's baby toolbar ( icon paddings )

### Step-by-step reproduction instructions

1) create button
2) check baby toolbar ( icon padding ) 

### Screenshots, screen recording, code snippet

![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/1be8bac5-634c-40f1-bd9a-37fded51d514)

<details open>
<summary>Checklist</summary>

- [X] Create `src/blocks/button-maxi/components/button-control/index.js` ✓ https://github.com/maxi-blocks/maxi-blocks/commit/8f92b2466b8b7904ba93d1230993defa18d33bdf

![Flowchart](https://raw.githubusercontent.com/maxi-blocks/maxi-blocks/sweep/assets/13d1a1eca1c50ffc7a4fd6368644a2abf0990735092b06e2aa2baf952be3292c_5231_flowchart.svg)
</details>

**Comment by kyrapieterse** [comment]
@dosu-bot suggest a code fix

**Comment by kyrapieterse** [comment]
@sweep-ai suggest a code fix
