### ISSUE TITLE
MaxiBlocks Theme

### ISSUE THREAD

**Issue by kyrapieterse** [maxi-blocks/maxi-blocks#5232]
### Description

The designs are in Google Drive. I suggest Sasha starts making them and then list all the problems in this issue and tackle them together

**Initialize Theme Structure**

- [x]  Create a new directory in wp-content/themes/ for your theme.
- [x]  Add a style.css file with the necessary theme metadata.
- [x]  Create a functions.php file.
- [x]  Initialize a basic index.html block template.

**Develop Basic Templates**

- [x] index.html: The catch-all template that serves as a fallback.
- [x]  404.html: For displaying 404 error pages.
- [x]  search.html: For displaying search results.
- [x]  single.html: For displaying single posts. This can serve as a generic template for any singular content type if no specific templates are provided.
- [x]  page.html: For displaying individual pages.
- [x]  single-{post-type}.html: For custom post types, replace {post-type} with the name of your custom post type, e.g., single-event.html for an "event" post type.
- [x]  archive.html: A generic template for displaying post archives.
- [x]  archive-{post-type}.html: For custom post type archives, replace {post-type} with the name of your custom post type.
- [x]  category.html: For category archives.
- [x]  tag.html: For tag archives.
- [x]  taxonomy-{taxonomy}.html: For custom taxonomies, replace {taxonomy} with the name of your taxonomy, e.g., taxonomy-genre.html for a "genre" taxonomy.
- [x]  author.html: For displaying an author archive page.
- [x]  date.html: For date-based archives (year, month, day).
- [x]  comments.html: Template for displaying comments and the comment form.
- [x]  header.html: Pattern for the website header.
- [x]  footer.html: Pattern for the website footer.
- [x]  sidebar.html: Pattern for the sidebar, if your theme has one.
- [x]  Create a directory or organizational method for your patterns.
- [x]  Content Patterns: Reusable designs for post content, like featured images combined with post titles, or custom layouts for displaying meta information.
- [x]  Entry Header Patterns: Common designs for post headers, e.g., title combined with categories and meta.
- [x]  Entry Footer Patterns: Common designs for post footers, e.g., tags, "Read More" links, or post navigation.
- [x] Front Page
- [x] Blog Home

**Styling**

- [ ]  Set up a base style for your theme in style.css.
- [x]  Enqueue additional stylesheets in functions.php, if needed.
- [x]  Develop styles for Gutenberg blocks to match your theme's design.
- [x]  Test styling in different browsers for compatibility.

**Implement Global Styles**

- [x]  Create a theme.json file to define global styles.
- [ ]  Configure global settings (colour palettes, typography, layout, etc.).
- [ ]  Explore options for users to add custom fonts' via server upload & theme.json https://www.myfonts.com/ or other such services. 

**Advanced Gutenberg Features**

- [x]  Create and register block patterns if needed.

**Theme Customization Features**

- [ ]  Implement add_theme_support() in functions.php for features like custom logos, color palettes, etc.
- [x]  Develop Customizer options for users to modify theme appearance, if desired.
- [ ]  Implement navigation menus, widget areas, etc.

**Performance Optimization**

- [x]  Minify and concatenate CSS and JS files.
- [x]  Optimize images and other assets.
- [ ]  Consider implementing a caching solution

**Testing**

- [x]  Use the Theme Check plugin to validate your theme.
- [x]  Conduct manual tests: check different post formats, pages, archives, etc.
- [ ]  Test with third-party Gutenberg blocks to ensure compatibility.
- [ ]  Check theme with accessibility tools to ensure it's accessible.

**Documentation**

- [ ]  Write a user guide detailing how to install and customize the theme.
- [ ]  Document any custom blocks or features specific to your theme.
- [ ]  Provide troubleshooting tips and common solutions.

**Packaging and Distribution**

- [x] Finish basic templates
- [ ] Generate translation files
- [ ] Check in the Theme Checker plugin
- [ ] Run wp unit tests https://github.com/WordPress/theme-test-data

**Bug fixes**
- [ ]  https://github.com/maxi-blocks/maxi-blocks/issues/5232#issuecomment-2009160419
- [ ] Footer template part randomly looses styles

**Comment by kyrapieterse** [comment]
Design files

Nav
![NML-PRO-14 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/30882fba-ce76-42d8-a369-041e4cbbe34c)
![NML-PRO-17 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/7526a9f5-80eb-4345-9b2c-b9aab436f14a)
![NML-PRO-18 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/f9a537d1-0f45-42b6-9b60-ce692b448b6b)
![NML-PRO-27 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/2c5e190d-7163-4d8e-999f-e5d779938a7c)
![NML-PRO-34 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/cb62120a-2d34-48ab-97a3-7efebccef90b)
![NML-PRO-35 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/418f307c-76a4-41f1-bcc9-eb00cfaf12ea)
![NML-PRO-36 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/26adb521-638a-47b8-9d4b-796dd86c21ad)

**Comment by kyrapieterse** [comment]
Design files
![Author 3 col copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/41d42a07-e3a9-4863-93fd-5d2068823629)
![Index  2 col copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/071b55dc-a234-4ef1-af77-3b90b2d21d21)
![Index  3 col copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/1f22871d-d8ea-4240-b168-5f3ca9597bf0)
![Page copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/74bcc989-f0a4-4102-873a-f61ebfaaba46)
![Search with contact copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/901c46e8-9bed-48b3-bfff-dc50865c6c78)
![Single copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/ee5c620e-5881-4df2-8dad-db7fd019e190)
![Single Full copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/f85e728d-c051-4bae-9469-687188e8a2ed)
![Single Sidebar copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/39455d40-8aa5-412b-95f6-4a5508ab7905)
![Author 2 col copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/47b24607-147a-4434-8fa8-ded95ce4c0c2)

![Archive 2 col copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/82d3ac5e-6e1e-4cf9-b360-3e746ea57777)
![Archive 3 col copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/680f0b91-4b9d-48e0-a837-c461594e1204)

**Comment by kyrapieterse** [comment]
Home and inside pages
![About1 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/38c85415-fe57-473d-9af5-48b217e8e6be)
![About2 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/4567693e-8f51-4337-8633-5cff5587f6c1)
![About3 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/891ed7cc-10ce-4f51-80e6-43cffab459d2)
![ATP-PRO-01 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/65d4443e-f595-49a1-955f-e792d89eab43)
![MT-HomePage copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/0fb70b07-1e83-447d-876c-52864b214698)
![MT-HomePage2 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/b7d3bbf5-9b73-4911-88c8-8956e8c6e0df)
![MT-HomePage3 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/7e180a2a-e3b5-43bd-bb1c-123e3dda6d4a)
![MT-HomePage4 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/621b0db6-94f1-419c-842c-8b5bf17831d1)
![MT-HomePage5 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/4cd8c6b1-1610-4685-bd4f-72d58c986e77)
![MT-HomePage6 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/eb47f63b-f233-440f-ab84-16ace92cd22b)
![Service1 copy 2](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/3386eedc-7f47-478e-b3dc-5544d97d2e5a)
![SSP-PRO-04 copy](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/e8691a1c-6d2b-4a86-9bea-7479d905b18d)

**Comment by elzadj** [comment]
What I need:
this info (I can copy from the plugin, just mark as "copy from the plugin"): 

/*
Theme Name: Twenty Twenty-Four
Theme URI: https://wordpress.org/themes/twentytwentyfour/
Author: the WordPress team
Author URI: https://wordpress.org
Description: Twenty Twenty-Four is designed to be flexible, versatile and applicable to any website. Its collection of templates and patterns tailor to different needs, such as presenting a business, blogging and writing or showcasing work. A multitude of possibilities open up with just a few adjustments to color and typography. Twenty Twenty-Four comes with style variations and full page designs to help speed up the site building process, is fully compatible with the site editor, and takes advantage of new design tools introduced in WordPress 6.4.
Requires at least: 6.4
Tested up to: 6.4
Requires PHP: 7.0
Version: 1.0
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain: twentytwentyfour
Tags: one-column, custom-colors, custom-menu, custom-logo, editor-style, featured-images, full-site-editing, block-patterns, rtl-language-support, sticky-post, threaded-comments, translation-ready, wide-blocks, block-styles, style-variations, accessibility-ready, blog, portfolio, news
*/

A screenshot, screenshot.png, 1200x900 px

**Comment by elzadj** [comment]
And this https://make.wordpress.org/themes/handbook/review/required/#1-licensing-copyright
Also take a note of https://make.wordpress.org/themes/handbook/review/required/#6-plugins

**Comment by ckp267** [comment]
> What I need:
> this info (I can copy from the plugin, just mark as "copy from the plugin"):


/*
Theme Name: MaxiBlocks Theme
Theme URI: [to be added]
Author: MaxiBlocks
Author URI: https://maxiblocks.com/go/theme-author
Description: The MaxiBlocks Theme, designed for versatility and innovation provides a wide array of templates and patterns suited for diverse website needs, including business showcases, blogs, and portfolios. The theme features style variations and full-page designs, speeding up site-building and compatibility with the latest WordPress features.
Requires at least: 6.2.2
Tested up to: 6.4
Requires PHP: 8.0
Version: 1.5.0
License: GNU General Public License as published by the Free Software Foundation; either version 2 of the License or (at your option) any later version and the Mozilla Public License, Version 2.0
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: maxiblocks
Tags: fse, block-editor, responsive, business, blog, e-commerce, full-site-editing, custom-colours, patterns, headers, footers
*/

**Comment by elzadj** [comment]
https://developer.wordpress.org/themes/releasing-your-theme/

**Comment by elzadj** [comment]
Note: 
1. Customizer with the site's logo option and Custom css option
2. Local font (Roboto) - disable it when plugin is active
3. A prompt to install maxi plugin
4. Translation-ready

**Comment by elzadj** [comment]
https://github.com/maxi-blocks/maxi-blocks/issues/4856

**Comment by kyrapieterse** [comment]
> Request: Blog pagination

maybe we can hack the default one to work with ours

**Comment by elzadj** [comment]
> > Request: Blog pagination
> 
> maybe we can hack the default one to work with ours

We can make the SC affect it by default, and make it look ok, but our own blogs don't really support pagination :thinking: 
I think we wanted to use slider for it before, maybe we can try it.

**Comment by kyrapieterse** [comment]
> > > Request: Blog pagination
> > 
> > 
> > maybe we can hack the default one to work with ours
> 
> We can make the SC affect it by default, and make it look ok, but our own blogs don't really support pagination 🤔 I think we wanted to use slider for it before, maybe we can try it.

cool. def need it lol

**Comment by elzadj** [comment]
Need for our templates to be affected by SC when the plugin is active
Need to minimize all css / js code
and of course test the speed / score

**Comment by elzadj** [comment]
- [ ] All plugin issues with tag https://github.com/maxi-blocks/maxi-blocks/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%A7%91%E2%80%8D%F0%9F%9A%92+need+for+theme+%F0%9F%A7%91%E2%80%8D%F0%9F%9A%92%22
- [ ] Fix previews for patterns on WP 6.5
- [ ] Try to optimize Patterns inserters and previews speed
- [ ] Add all custom patterns from the sheet
- [ ] _Finish basic templates_
- [ ] _Generate translation files_
- [ ] _Check in the Theme Checker plugin_
- [ ] _Run wp unit tests https://github.com/WordPress/theme-test-data _
