### ISSUE TITLE
DB warning on plugin install

### ISSUE THREAD

**Issue by elzadj** [maxi-blocks/maxi-blocks#5300]
### Description

Need to adjust the MySQL warning styles, make it dismissible + add mariaDB detection.

**Comment by ckp267** [comment]
Dismissible warning notice means you can click the 'x' and it stays hidden after that.

Yes. But I think maybe we should let it reset after a plug-in update so we can remind people? What do you think. I'm trying to create list support not more support

I can do it, yes. Show again after the update https://developer.wordpress.org/reference/hooks/upgrader_process_complete/
