### ISSUE TITLE
Freezes due to swapping between blocks

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5323]
### Description

it has accumulative effect.
Add ib, blocks, use ib preview and repeater, after some moment, you will see freezes

more time in editing, without update and reload > longer freezes

### Step-by-step reproduction instructions

1) Add ib, blocks, use ib preview, after some moment, you will see freezes

### Screenshots, screen recording, code snippet

https://jam.dev/c/d37361f0-f26f-4a67-a557-f5624874329f

https://github.com/maxi-blocks/maxi-blocks/assets/88893350/fb53062c-8402-4f40-896f-80bd7c7b103f

### URL and/or Code editor

[code for test.txt](https://github.com/maxi-blocks/maxi-blocks/files/13663178/code.for.test.txt)

[code for test 2.txt](https://github.com/maxi-blocks/maxi-blocks/files/13663363/code.for.test.2.txt)

**Comment by Marko64** [comment]
Here's a new page with just a bunch of rows and columns, no other blocks, IB or any settings changed:
https://jam.dev/c/04581dee-56ec-46a6-814b-6ac64cb3521d
