### ISSUE TITLE
Logic of closing SC window

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5325]
### Description

I guess, SC window should be closed after second click to main MAXI toolbar button

### Step-by-step reproduction instructions

1) click to MAXI toolbar button
2) click to SC button to call SC window
3) click to MAXI toolbar button again > SC window is not closing

### Screenshots, screen recording, code snippet

https://jam.dev/c/6afa4742-00bc-4f61-823b-7a6351d073a1

**Comment by kyrapieterse** [comment]
MVP - fine for now
