### ISSUE TITLE
Link`s hover colour should be higher than visited colour

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5336]
### Description

If you click on the tag > it assigns visited color > and hover color doesn't work anymore
I want the hover color to work always.

### Step-by-step reproduction instructions

1) add link to some text
2) set different colours for Link, hover and visited
3) click to link
4) hover colour does not work anymore

### Screenshots, screen recording, code snippet

https://jam.dev/c/e43d5ca7-62a9-48ca-9d7f-9cb4dd036a4f

![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/41f7d343-615e-4604-a6c0-1090a7e31f3a)

**Comment by Marko64** [comment]
Can't reproduce. Also it seems it works on one product but not on others on your video? Can you share the page code please.

**Comment by Olekrut** [comment]
@Marko64  code is any of last blocks, or create link, set normal, active and visited the same colour and another for hover > click to link > and try hover for it link

**Comment by Olekrut** [comment]
FF
[link.webm](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/ead2c969-2518-40c6-8d1d-d6f8f37a2806)

**Comment by Olekrut** [comment]
https://jam.dev/c/38bcfcf4-2cb6-4264-a7df-3b1a90f4634b
