### ISSUE TITLE
UI and other small fixes

### ISSUE THREAD

**Issue by Marko64** [maxi-blocks/maxi-blocks#5342]
### Description

The arrow icon is hardly visible, let's make it darker.

### Step-by-step reproduction instructions

Go to MB dashboard settings and check the icon in the top right corner of the accordions.

### Screenshots, screen recording, code snippet

![Screenshot_3](https://github.com/maxi-blocks/maxi-blocks/assets/19425503/5c22f2bd-b1b8-4037-890d-916f2b4c41d0)

**Comment by kyrapieterse** [comment]
Change support link

**Comment by ckp267** [comment]
### For style cards library please (see screenshot)

1. Update the button text from "Save" to "Preview"  (note capitalisation)
2. Keep "Saved" if it is already in the local db.

### remove crisp.chat live chat script toggle option.   (see screenshot) 

Keep the shortlink as is - no change. https://maxiblocks.com/go/help-center

![image](https://github.com/maxi-blocks/maxi-blocks/assets/7437580/8c603597-e1a5-4d81-93cd-4f2d7e0de7ae)
