### ISSUE TITLE
Conflicts related with Image-block hover effects

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5346]
### Description

Originally posted in https://github.com/maxi-blocks/maxi-blocks/pull/5339#pullrequestreview-1787556479

1) if enable image-maxi hover and any else hover ( for example box-shadow ) hover-in transition does not work correct - https://jam.dev/c/0b8ce821-afe6-4049-b264-a292d4eb1c52
Check split in/out, guess, there is conflict
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/77b8dbe3-dfd3-480e-a702-9f32f502e619)
2) Check for all transform options ( zoom, slide, rotate ) - trigger field is "img" , is not working correct, - https://jam.dev/c/1d3695d7-6f0d-4f5c-877c-d1f6f2d06d86
3) For gray scale and sepia hovers - transition does not work - https://jam.dev/c/31ed34cd-d297-42e7-a191-0eb7ebaaa0c6
4)
4.1) animation in image settings use transform for img, so there are conflict - we cant use both - https://jam.dev/c/306c4e51-872a-41a7-9a96-7d5a6f666ccc
4.2) The same with scroll - we cant use hover animation and scroll - https://jam.dev/c/03ad0426-ede9-4003-bfcb-939b920fd3dc
5) if use hover with disabled "Extend outside boundary" > guess, settings ( box-shadow, borders, etc. ) are not visible, because overflow:hidden - is not intuitive for nubbies - https://jam.dev/c/85f00dcd-aa7d-420d-8bc2-eeec33bbcd9a
6) ( not very important )  text hover - when you are changing animation type - first hover-in is not working correct - https://jam.dev/c/a727ffe9-4a96-42b8-b9c6-1bfdfeddab14
7) Sure, that we will have conflicts with IB as well

We have a lot of conflicts with hover animations - so 
1) need a warn massage
2) disallow part of used  options.
3) or best way as for me - 
it should work like quick styles for button
Example when we use Zoom hover animation > it should enable related transform scale setting in advanced tab
the same with slide, etc

### Step-by-step reproduction instructions

1) check description

**Comment by kyrapieterse** [comment]
going to remove
