### ISSUE TITLE
Hover effect. Add warn messages

### ISSUE THREAD

**Issue by Fybex** [maxi-blocks/maxi-blocks#5354]
5) if use hover with disabled "Extend outside boundary" > guess, settings ( box-shadow, borders, etc. ) are not visible, because overflow:hidden - is not intuitive for nubbies - https://jam.dev/c/85f00dcd-aa7d-420d-8bc2-eeec33bbcd9a

_Originally posted by @Olekrut in https://github.com/maxi-blocks/maxi-blocks/pull/5339#pullrequestreview-1787556479_

**Comment by kyrapieterse** [comment]
We wait for support
