### ISSUE TITLE
Bug with colours due to changing tone

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5360]
### Description

Some of blocks, SVG, texts are not changing colours after changing tone ( only after click to it )

### Step-by-step reproduction instructions

1) load SML-PRO-162 ( for example )
2) change tone
3) check colours for all svg and texts

### Screenshots, screen recording, code snippet

https://jam.dev/c/a12deb02-128c-4e30-a6cb-2bd050b12df2

**Comment by kyrapieterse** [comment]
https://jam.dev/c/cfbb8919-4a74-4f23-a7c6-ce873babf9b6

words fine for me on the current repo version

**Comment by elzadj** [comment]
> https://jam.dev/c/cfbb8919-4a74-4f23-a7c6-ce873babf9b6
> 
> words fine for me on the current repo version

I can re-create on master. Scroll down please, the arrows colour is wrong starting from the 3rd arrow: 

![screenshot-wordpress local-2023 12 21-18_06_01](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/4cdad4ba-d4ed-4aa9-9718-8f54497d6dda)

**Comment by Olekrut** [comment]
Not sure, but looks like brakes only main white and black colours
