### ISSUE TITLE
Bug with displaying frontend on different pages Round 2

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5361]
### Description

Was similar in https://github.com/maxi-blocks/maxi-blocks/issues/5155

### Step-by-step reproduction instructions

1) create page with container ( light tone )
2) duplicate page ( i ve used Yoast Duplicate Post plugin for it )
3) change tone to dark on duplicated page and publish 
4) check tone on frontend for first page

### Screenshots, screen recording, code snippet

https://jam.dev/c/53033064-019f-4097-8509-d0c840614e8a

**Comment by elzadj** [comment]
Happens only when you Duplicate Post.
