### ISSUE TITLE
Weird behavior with IB for BG Layers

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5369]
### Description

Master

### Step-by-step reproduction instructions

1) Load PTML-PRO-82
2) check hover, Image should not disappear

### Screenshots, screen recording, code snippet

https://jam.dev/c/447fd5c4-fccc-4257-b6b9-563f547ca60a

**Comment by Fybex** [comment]
There's quite an old version of this template: `1.0.0-RC1`. So I suggest to just run styles update by changing some setting value for a moment. It's some old issue, which isn't reproducible on new blocks. As I can understand, there's no a lot of patterns with a problem like this, so it's the best way to fix it @Olekrut 

https://github.com/maxi-blocks/maxi-blocks/assets/46112160/19241b62-c4c6-4cab-bdc7-f3e818c55764
