### ISSUE TITLE
Cant open editor on page because bug with repeater

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5380]
### Description

Cant attach video, but it happens after enabling repeater for this row
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/5ec30fd8-9af9-4f46-990a-f0f440c32fed)

### Step-by-step reproduction instructions

1) try to open editor for attached page

### Screenshots, screen recording, code snippet

![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/832bd017-1a67-4bdf-ac54-ead0c1c708f0)

### URL and/or Code editor

https://3devdemo.maxiblocks.com/story-mix-light-sml-pro-part-11/

**Comment by elzadj** [comment]
[code.txt](https://github.com/maxi-blocks/maxi-blocks/files/13810287/code.txt)
