### ISSUE TITLE
Page preview does not work before publish

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5388]
### Description

Page preview does not work before publish

### Step-by-step reproduction instructions

1) Create page
2) add some pattern or block
3) click to preview page ( not publish before )

### Screenshots, screen recording, code snippet

https://jam.dev/c/098a25b6-ef81-409a-a0f4-4c8331d66c1f

**Comment by kyrapieterse** [comment]
We have had this before 🤔

**Comment by Olekrut** [comment]
Almost sure, that this glich was on master, but cant re-create anymore. Probably it was on some of the test PRs) will test again before update, then we will know for sure

**Comment by kyrapieterse** [comment]
Let's close it
