### ISSUE TITLE
Extra link`s toggles are not working for DC text-block 

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5420]
### Description

Extra link`s toggles are not working for text-blocks where DC is enabled

### Step-by-step reproduction instructions

1) create Text block
2) Enable DC
3) Enable DC link 
4) try to enable any extra toggle for link under

### Screenshots, screen recording, code snippet

https://jam.dev/c/825de117-d071-40c4-a115-e87542ac3681
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/a9582d4f-e3ac-4e72-b352-c8295bf0b334)

**Comment by myroslavve** [comment]
this is fixed in https://github.com/maxi-blocks/maxi-blocks/pull/5489, so linked it, will be closed when the PR is merged.
