### ISSUE TITLE
Need to add accumulation for relation: get current

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5451]
### Description

Relation: get current does not work correct, because we don't have accumulation for get current
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/d8c3252d-1b8a-4478-8c55-69ecb44bb441)

### Step-by-step reproduction instructions

1) Add our blog pattern to some FSE template ( should be a few different posts for cat or tag )
2) check frontend

### Screenshots, screen recording, code snippet

https://jam.dev/c/9c7a35cc-46ef-4f5a-8cb4-95f039a07edc

### URL and/or Code editor

https://2devdemo.maxiblocks.com/category/pbgd-pro-23/
https://2devdemo.maxiblocks.com/tag/blog/

**Comment by elzadj** [comment]
Just adding an accumulator is not going to help. Need to add current posts for Category or something like this.
