### ISSUE TITLE
Template library doesn't work for FSE>pages

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5452]
### Description

Template library doesn't work for FSE>pages
Master

### Step-by-step reproduction instructions

1) open FSE>Pages
2) try to open Template library by toolbar

### Screenshots, screen recording, code snippet

https://jam.dev/c/51866e47-c0a6-4898-89f7-a6c8ce70c48c

**Comment by elzadj** [comment]
FSE - Templates - Pages and Page with Sidebar are affected. Only from the Toolbar.
