### ISSUE TITLE
Full width videos from library loading wrong on Backend 

### ISSUE THREAD

**Issue by dashaversha** [maxi-blocks/maxi-blocks#5461]
### Description

Full width videos from library loading wrong on Backend, Frontend is ok. Disapper after page reloading or adding pattern with video more then one time to one page. 

### Step-by-step reproduction instructions

1. Add SML/SMD-PRO-49 
2. Check height of video on Backend

### Screenshots, screen recording, code snippet

https://jam.dev/c/6523bb66-c6bf-4313-b8b0-9301f15d41a3

**Comment by elzadj** [comment]
Seems like one with the not-Chrome browsers :thinking:
