### ISSUE TITLE
Link for button canvas.

### ISSUE THREAD

**Issue by myroslavve** [maxi-blocks/maxi-blocks#5470]
### Description

Button-block, link should be adding to canvas area (wrapper) otherwise link will not work on designs where we are using BG Layers
https://jam.dev/c/2de04a6a-fe96-4f9e-b87f-9528d616a24d

_Originally posted by @Olekrut in https://github.com/maxi-blocks/maxi-blocks/pull/5459#pullrequestreview-1908620940_

**Comment by Olekrut** [comment]
https://jam.dev/c/67994145-0f9b-4003-8989-2b9ae4e09dc2
guess, not just canvas, we should have ability to chose > block or canvas
