### ISSUE TITLE
DC link is removing from old DC blocks

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5482]
### Description

 If load blog older 24 jan, DC link will be removed for authors, cats and tags. 
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/71c69775-d7fb-4376-bc9b-cf6968a6e70c)
Probably, related with https://github.com/maxi-blocks/maxi-blocks/pull/5459

### Step-by-step reproduction instructions

1) Chose brunch issue-5407
2) pick blog loaded to library earlier 24 jan ( PBGL-PRO-101 - example )
3) check DC link for author, cat ot tag

### Screenshots, screen recording, code snippet

https://jam.dev/c/204fe978-3a70-4b85-9191-a527fa12c5fd

**Comment by Olekrut** [comment]
@elzadj 
And if use old pages with DC links > frontend does not work and check link colours, they are not working
https://jam.dev/c/850ecc6a-1a6e-4a33-bbd2-3c967508614b

**Comment by elzadj** [comment]
@myroslavve please note that we removed your previous fix to be able to update the plugin https://github.com/maxi-blocks/maxi-blocks/pull/5484
