### ISSUE TITLE
Conflict with Duplicate Page plugin.

### ISSUE THREAD

**Issue by kyrapieterse** [maxi-blocks/maxi-blocks#5483]
When using this plugin it break MaxiBlocks

https://wordpress.org/plugins/duplicate-page/

I have a video - ping me for it

**Comment by elzadj** [comment]
Details: looks like it strips some slashes and produces something like ```>u003cstrongu003eRaving Reviews, Happy Storiesu003c/s```

**Comment by myroslavve** [comment]
Users have to select "Gutenberg editor" in the duplicate plugin settings. When I selected it, it duplicates pages right.
![image](https://github.com/maxi-blocks/maxi-blocks/assets/53875005/9efd66d0-bdea-4f10-a1fc-2335dbb392a1)

So @kyrapieterse could you check if this works for you?

**Comment by kyrapieterse** [comment]
Emailed the client got no reply so closing for now. We can reopen it if we need to
