### ISSUE TITLE
UI confusion with ACF and DC CPT

### ISSUE THREAD

**Issue by elzadj** [maxi-blocks/maxi-blocks#5486]
### Description

Found a bit of a confusion with the UI if we create CPT with AFC (y, you can do it). 
They show under both sources: Wordpress and ACF, but only the WP one works. 

Not sure what's the best way to fix it here - hide it under ACF, or just make it work there too.

### Step-by-step reproduction instructions

1. Add CPT and CT with ACF
2. Check the DC / CL options
3. Choose ACF - your created CPT

### Screenshots, screen recording, code snippet

![screenshot-wordpress local-2024 03 06-12_43_03](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/3de4098b-c2e8-44e6-8fe6-1423d7c87948)

**Comment by myroslavve** [comment]
For me, ACF DC fields work on master, for example here I have a custom post type "Movie" with custom field "Review" and it seems to work:

![image](https://github.com/maxi-blocks/maxi-blocks/assets/53875005/2f22bc98-68a2-45e6-82c0-2ff27764242b)

The only thing is, when changing in CL, DC blocks don't select default (or first) "ACF field" when getting content until you click on them, so they don't get any content and return "No content found" until you click on them. So I will fix this here as well.

**Comment by elzadj** [comment]
CL ACF UI is even more confusing:

![unnamed (14)](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/b872d009-03ff-4866-ae1d-13f9d3309c07)

**Comment by Olekrut** [comment]
[acf exports , and cpt items.zip](https://github.com/user-attachments/files/16014827/acf.exports.and.cpt.items.zip)
