### ISSUE TITLE
Navigation's sub-menu in the bottom

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5500]
### Description

IF Navigation's sub-menu in the bottom, we can't see it.
Need script as for our toolbar

### Step-by-step reproduction instructions

1) add nav with sub-menu to bottom
2) check that you cant see it

### Screenshots, screen recording, code snippet

https://jam.dev/c/23b5e3dc-baf7-41e4-96d5-d830767cca92

**Comment by elzadj** [comment]
Is it the same if you use a default Nav menu without maxi? I don't think sub-menus should be used in the footer in general by logic, maybe just add padding to the bottom.
