### ISSUE TITLE
Relation: get current is gone

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5504]
### Description

Relation: get current is gone

### Step-by-step reproduction instructions

1) check relation in DC

### Screenshots, screen recording, code snippet

![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/48626945-c306-4d34-851c-33dffa14a700)

![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/d12e9352-2583-4456-88d5-b4bdd721d9b5)

**Comment by elzadj** [comment]
What WP post type are you on? Page, Post, FSE, Pattern?
