### ISSUE TITLE
nav on backend does not look correct ( should be icon or word menu )

### ISSUE THREAD

**Issue by kyrapieterse** [maxi-blocks/maxi-blocks#5506]
### Description

![image](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/fffc0089-0071-4b08-8cdc-bf0f0de28166)

**Comment by Olekrut** [comment]
https://github.com/maxi-blocks/maxi-blocks/issues/5416#issuecomment-1930469524
point 5
