### ISSUE TITLE
Need for Theme Templates

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5543]
### Description

1) need to check how SC influence to all native blocks
for example: font-family from SC does not work for pagination blocks
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/fa98791c-efe3-4e34-822b-707d346ce421)
2) need to check settings for comment form - BG, borders, etc
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/e0ae39fa-5a3c-4dab-83a0-b2cc33dae307)
3) everything in post template works as header, because title is parent, need to do smth with it, because w should use CSS for font-size
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/84222c70-e0aa-4051-936b-de0e748632c6)
4) some settings for native blocks as like H-tags we can set only in toolbar, but toolbar appears randomly, not all the time
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/f629d66c-e9d6-4ace-b7ef-6cde4bc6bd78)

### Step-by-step reproduction instructions

1) add native pagination inside our block and check font-family on frontend
2) add comment form inside our block and check in incognito
3)  add post template block inside our block and check font settings 
4) add native title and try to call toolbar, sometimes it starts to work after reload

### Screenshots, screen recording, code snippet

.

**Comment by elzadj** [comment]
1. Native navigation for posts, native navigation for blog, what else? 
3. That's not a bug, need something to group items inside the list for the li elements, so WP uses h3. Add title, date, and excerpt to a group like this: 
![screenshot-wordpress local-2024 04 12-15_40_16](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/0e543571-4e7c-4c9c-9298-f429011c457e)
then it uses group inside li, not h3.
4. Can't fix gutenber blocks.
