### ISSUE TITLE
CSS transitions doesn’t work in Firefox

### ISSUE THREAD

**Issue by kyrapieterse** [maxi-blocks/maxi-blocks#5546]
https://maxiblocks.com/demo/block-pattern-image/pure-image/pil-pro-71/

these don't work in Firefox

**Comment by Olekrut** [comment]
https://maxiblocks.com/demo/block-pattern-team/pure-team/ptml-pro-51/
the same

**Comment by Olekrut** [comment]
looks like the same for all Transform hovers ( IB )
