### ISSUE TITLE
Beta theme bugs

### ISSUE THREAD

**Issue by kyrapieterse** [maxi-blocks/maxi-blocks#5555]

**Comment by Marko64** [comment]
Double sidebar:
![unnamed](https://github.com/maxi-blocks/maxi-blocks/assets/19425503/2230c78a-c95d-41cd-926a-5f17a8d44eff)

**Comment by Marko64** [comment]
Opening customizer throws some warnings:
![image](https://github.com/maxi-blocks/maxi-blocks/assets/19425503/548fbbc5-076d-4fd4-9d38-4b63a9f9102f)

**Comment by elzadj** [comment]
Fixed both here: https://github.com/maxi-blocks/maxiblocks-theme , we can test later when we do it on sites.
