### ISSUE TITLE
TT4 theme + site page template switch causes frozen page 

### ISSUE THREAD

**Issue by ckp267** [maxi-blocks/maxi-blocks#5558]
### Description

Likely a micro update to TT4 & wordpress in combination. 

I just tested TT3 exact same steps IT WORKS! 

### Step-by-step reproduction instructions

See video - too many steps
https://iframe.mediadelivery.net/play/173265/9af8612a-c44a-435f-9e7b-d35612145e70 

Also the WordPress FSE ui is so confusing its not clear if im supposed to CLICK to insert or CLICK AND DRAG - so I ended up with double footer -that i had to delete - stuck in a loop - so beware that part was not intentional. 

Check the screenshot for the permissions notice error. I was admin - 100% had full permissions.
Happens when i create a header template part. Show in video too. 
Same permissions notice happened in tt3

![chrome_DigmWkfpgZ](https://github.com/maxi-blocks/maxi-blocks/assets/7437580/a88d961a-53b5-4998-9b27-aa39627dc2ad)
![chrome_maaKHt1vZX](https://github.com/maxi-blocks/maxi-blocks/assets/7437580/4f862215-0fba-4fc3-8f27-7379c10c43e6)
![chrome_ei9rp0FfPM](https://github.com/maxi-blocks/maxi-blocks/assets/7437580/e6f0c54b-fd89-4c88-a094-04c5bf34ae87)
![chrome_MSRZwbORVH](https://github.com/maxi-blocks/maxi-blocks/assets/7437580/a42dc824-abaa-4ebb-8eb6-55f5ffe44291)
 & tt34

### URL and/or Code editor

[site-health-tt4-maxi-bug.txt](https://github.com/maxi-blocks/maxi-blocks/files/15047863/site-health-tt4-maxi-bug.txt)
[tt4-maxiblocks-site-template-bug-error-log.txt](https://github.com/maxi-blocks/maxi-blocks/files/15047864/tt4-maxiblocks-site-template-bug-error-log.txt)

**Comment by ckp267** [comment]
More feedback from our support channel. i @ckp267 was able to get it to work in TT3 while a **_customer_** used TT3 on local and then had the same screen freeze issue when trying to swap template.

I Swear that UI changed - the  previous version of WordPress actually showed you the template name - and you could click on it. Now it's loading the site template ui. So seems like a new thing they added in a recent update that we've just discovered. 

-- From support ...  --- screenshot is anonymised.
>> I'm sorry I forgot to mention this before.. After I downgraded MariaDB and did other required settings I already had to reinstall fresh WP. There I remembered that you've been using TT3 in the video so I already used TT3 this time and got the same result.

![image](https://github.com/maxi-blocks/maxi-blocks/assets/7437580/609a7d90-8fec-4985-bb13-0dc0b0c12f9d)

**Comment by elzadj** [comment]
Looks like a random template ("Page no title" in that case) froze while loading header / footer with maxi.
It shouldn't do it tho, it should show the preview image and stop loading everything as soon as it hits the first maxi block inside.

But the maxi blocks are in the template's parts, not the template itself, so looks like it breaks the preview image and continues to load the Gutenberg with everything, and then it freezes.
