### ISSUE TITLE
No way to set width for Avatar with DC

### ISSUE THREAD

**Issue by kyrapieterse** [maxi-blocks/maxi-blocks#5562]
### Description
Max width for the avatar in maxi and author blocks is 96x96. Avatar block allows up to 240px

![image](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/8451c5f3-8e24-4bac-a9ac-ff4d6a3ba5e0)
![image](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/0b38e8af-c9c8-451a-9f87-b78dbb45218f)

### Step-by-step reproduction instructions

Add DC avatar and Avatar block, compare the max size.

### How to fix it

Check how the Avatar block gets bigger image from gravatar

**Comment by myroslavve** [comment]
I have two options for this issue:

1. Add a slider to enable users to select avatar size:
![image](https://github.com/user-attachments/assets/953af651-4f0e-44cf-8727-96232a74ea5f)

2. Load the biggest size image, unless width for an image block is set. If the width is set, then load the image with size 2 times the width, like gutenberg avatar block does.

If I do the second option the loaded image will be larger than necessary on average, but the user won't have to think about it unlike the first option. Not sure which is better in this situation.

**Comment by myroslavve** [comment]
Decided to go with the first option
