### ISSUE TITLE
maxi does not work if create new template

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5571]
https://jam.dev/c/2afd3e18-ca15-4c14-8c60-99460261575d
not sure, maybe need to create another issue for that?

chose from drop down menu  > Create new template > Maxi does not work there

_Originally posted by @Olekrut in https://github.com/maxi-blocks/maxi-blocks/pull/5563#pullrequestreview-2020365692_

**Comment by elzadj** [comment]
Could be the same as https://github.com/maxi-blocks/maxi-blocks/issues/5570
