### ISSUE TITLE
DC content is not rendering on frontend

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5577]
### Description

DC content is not rendering on frontend

### Step-by-step reproduction instructions

1) Upload blog №24
2) use posts with content

### Screenshots, screen recording, code snippet

https://jam.dev/c/c4885c49-756e-43a6-b15e-2b6797f8c8b2

### URL and/or Code editor

[post content.txt](https://github.com/maxi-blocks/maxi-blocks/files/15222161/post.content.txt)

**Comment by elzadj** [comment]
Has nothing to do with the blog pattern - most likely the character limit is less than the gutenberg code amount. Need to try to limit it after we get the content without the blocks code.
