### ISSUE TITLE
Issues when switching category

### ISSUE THREAD

**Issue by elzadj** [maxi-blocks/maxi-blocks#5593]
Happens when you switch the category in the settings, mostly each even time. 

              Hidden for blogs are not working correct after changing cat in CL
https://jam.dev/c/bf0af755-3364-4f8e-be86-af8ce0c197df

_Originally posted by @Olekrut in https://github.com/maxi-blocks/maxi-blocks/pull/5590#pullrequestreview-2070978950_

**Comment by Olekrut** [comment]
1.8.5
looks like the same thing
on the 2nd page of the pagination
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/366cabde-b36c-4069-8f5c-9b6e38c229b6)
-then I chose a category with two posts, and there was no content found
-then after that I chose a category with a lot of posts 
and no content found appeared on the 3rd column of the first page of the pagination
![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/ff6ae130-12f7-425e-bdc0-09aaf5fe6f1c)
