### ISSUE TITLE
Need to change bird icon for quick styles for button block

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5605]
### Description

Need to change bird icon for quick styles for button block

### Step-by-step reproduction instructions

need to change bird icon to another one, guess fjust arrow ( better for future )

### Screenshots, screen recording, code snippet

![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/10ac27cd-d459-4e31-a275-a164cae3f1df)

**Comment by kyrapieterse** [comment]
https://drive.google.com/open?id=1aGGhIVdcAZLQ4pwFUeOpXXrKV0maxh8h&usp=drive_fs

**Comment by kyrapieterse** [comment]
![image](https://github.com/maxi-blocks/maxi-blocks/assets/2478274/34c1f2f3-53ed-49bb-9294-1a1d7db18b6a)
 this one
