### ISSUE TITLE
Need to remove wrong tooltip

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5619]
### Description

Need to remove wrong tooltip

### Step-by-step reproduction instructions

1) create text
2) click to typography in toolbar
3) hover line-height input field

### Screenshots, screen recording, code snippet

![image](https://github.com/maxi-blocks/maxi-blocks/assets/88893350/10cc2f72-f22d-45e1-9094-73bf6ae704d6)

**Comment by elzadj** [comment]
Can't recreate, a video + code would be nice.

**Comment by myroslavve** [comment]
> Can't recreate, a video + code would be nice.

Same

**Comment by elzadj** [comment]
@Olekrut ^^

**Comment by Olekrut** [comment]
@elzadj @myroslavve 
https://jam.dev/c/0e81dc8d-47a7-4839-9b77-eca538a03c58
load Hero-PRO-61
idk why, maybe only for old blocks
cant reproduce with new blocks
