### ISSUE TITLE
Wrong size of video block on backend if aspect ratio: none

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5629]
### Description

Wrong size of video block on backend if aspect ratio: none
should be size of overlay image

### Step-by-step reproduction instructions

1) create video and add overlay image or add SML-PRO-49
2) set aspect ratio: none for video
3) check frontend and backend

### Screenshots, screen recording, code snippet

https://jam.dev/c/23d8dfe2-c7f0-4d99-9ad9-3adb140875a7

**Comment by hunxjunedo** [comment]
@elzadj  I can help with this.

**Comment by Olekrut** [comment]
https://jam.dev/c/961007b0-4e00-4c85-ab8a-891bae6654b5

1) create video and add overlay image or add SML-PRO-49
2) set aspect ratio: none for video
3) check frontend and backend ( everything is fine )
4) refresh editor page or close and open again
5) check backend after it

**Comment by elzadj** [comment]
@myroslavve @Olekrut can't re-create on local, maybe try on a dev site? Then you can link us to it.

**Comment by Olekrut** [comment]
https://jam.dev/c/67ce6a75-8246-456b-97c2-984923e5a45b
