### ISSUE TITLE
FSE. Sometimes is disappearing relation - by current 

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5671]
### Description

FSE. Sometimes is disappearing relation - by current 
Tested on master and 3devdemo

### Step-by-step reproduction instructions

1) try to create single item post ( specific )
2) save/reload or past pattern from another page or site
3) it is appearing if open original single post template and add there maxi with current > then this relation is appearing everywhere
4) 50/50 random bug

### Screenshots, screen recording, code snippet

https://jam.dev/c/dffcfb64-1680-47db-b6bb-58d3a1ac8266

**Comment by dashaversha** [comment]
https://jam.dev/c/580d649a-b02d-424a-b95f-bfc4207f1285

It was ready pattern with "get by current..' on all dynamic parts,if you dont touch it - it is looks correct, but if you try to change anything and resave,you get this bug,"get by current.." just dissapear
To fix it I go to Single Posts and back,but need to turn on it everywhere again 

P.S. Sasha suggests that can happen with copied pattern from devdemo,but pattern in the video fully created in FSE,so I dont think this is related

**Comment by dashaversha** [comment]
![image](https://github.com/user-attachments/assets/ff66ce0d-ab7b-441e-a2a2-4747703a9308)
https://jam.dev/c/5e1c4d16-1f51-44a5-8702-b4cab5c1df6b 
Bug on the tag while changing "by current..." to "by category" on the pattern copied from FSE
