### ISSUE TITLE
Responsive bug for old pages

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5748]
### Description

I saw this bug on https://maxiblocks.com/wordpress-websites/maxi-blocks-a-guide-to-the-wordpress-design-library/showcase/
and 3devdemo

backend is ok, frontend - no
how to fix:
change value > save
just resave of page doesn't work, need to change value where we notice bug

noticed for flexbox, max-width of row, paddings of containers...

### Step-by-step reproduction instructions

1) check description and video

### Screenshots, screen recording, code snippet

https://jam.dev/c/6cbde40e-f53d-45a2-b464-338b5f5f5621

**Comment by elzadj** [comment]
Fixed in https://github.com/maxi-blocks/maxi-blocks/pull/5749
