### ISSUE TITLE
Bug with IB on old patterns

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5772]
### Description

Bug with IB on old playground pattern. Ib is not working on frontend at all or working not correct
Guess, related with opacity, because all broken patterns have it

### Step-by-step reproduction instructions

1) load playground pattern 1, team - 60, 77, 113, 114, etc
2) check hover on frontend and in library

### Screenshots, screen recording, code snippet

[bug playground.webm](https://github.com/user-attachments/assets/5573565d-3b60-4a69-8c49-546b9aa565b7)

**Comment by elzadj** [comment]
Fixed in 2.0.0
