### ISSUE TITLE
WP 6.7 bugs

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5777]
### Description

WP 6.7-RC-1

1) The cloud does not work 
https://jam.dev/c/e842b5e0-4434-4601-aa0c-e4827f3826d2
2) not sure, but speed got a bit slower as for me, Clicking, moving blocks...
3) bug with appenders
https://jam.dev/c/6c65500a-30a3-42cf-9628-7ee330ded47f
![image](https://github.com/user-attachments/assets/0a5f3028-1ef8-44cb-88b1-977862abde52)
4) buttons save and activate look like active all the time ( need to fix styles )
![image](https://github.com/user-attachments/assets/f46a6c6d-577f-43ac-b4b9-271331202182)

### Step-by-step reproduction instructions

.

**Comment by elzadj** [comment]
> ### Description
> WP 6.7-RC-1
> 
> 1. The cloud does not work
>    https://jam.dev/c/e842b5e0-4434-4601-aa0c-e4827f3826d2

Works fine for me, maybe you need to clean the cache, or maybe it was your local? You can update on a dev site and test there, if you want to.

> 2. not sure, but speed got a bit slower as for me, Clicking, moving blocks...
I don't really see it, but maybe we need to test it more. 

3, 4 - going to fix

Important: I've noticed that some columns are breaking on some pages, please test several pages randomly, and report here, @Olekrut  

An example of a broken page from a cloud (it's fine on 6.6.2): Architecture ARCP-PRO-06. Maybe also open some old pages to check them in the editor too.

**Comment by Olekrut** [comment]
yes, cloud is working on test site

5) https://jam.dev/c/54b8d8c5-072b-4fa4-87c9-7c8d927a89fc
blocks are broken ( HOD-PRO-134 ) if to load it on FSE ( page template on the video )
